In [ ]:
result = 0 
for i in range(100) :
    result += i

    print(result)

0
1
3
6
10
15
21
28
36
45
55
66
78
91
105
120
136
153
171
190
210
231
253
276
300
325
351
378
406
435
465
496
528
561
595
630
666
703
741
780
820
861
903
946
990
1035
1081
1128
1176
1225
1275
1326
1378
1431
1485
1540
1596
1653
1711
1770
1830
1891
1953
2016
2080
2145
2211
2278
2346
2415
2485
2556
2628
2701
2775
2850
2926
3003
3081
3160
3240
3321
3403
3486
3570
3655
3741
3828
3916
4005
4095
4186
4278
4371
4465
4560
4656
4753
4851
4950


In [ ]:
x = 100.01, 100

print(x)
#both int and float

(100.01, 100)


In [ ]:
l = list (range(25))




In [ ]:
type(l[0])




int

In [ ]:
l2 = [str(c) for c in l]
l2

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24']

In [ ]:
#int as str.
type(l2[3])

str

In [ ]:
l3 = [True, 2, "3,3", 3.2]

[type(item) for item in l3]

[bool, int, str, float]

Fixed Type of Arrays n Phyton 

In [ ]:
import array
L = list(range(10))
K = array.array("i", L)
K

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
J = list(range(10))
P = array.array("fq" , L)
P

#anlamadim valla

TypeError: array() argument 1 must be a unicode character, not str

Creating arrays from Phyton Lists

In [ ]:
import numpy as np

np.array ([1, 2, 4]) 

array([1, 2, 4])

In [ ]:
js = np.array([1,3,4])

x = np.array[11,1,2]

print(x,js)

In [ ]:
r = np.reshape( js, (2,3))

r

ValueError: cannot reshape array of size 3 into shape (2,3)

 - One Dimensional Subarrays - 

In [ ]:
import numpy as np

x = np.arange(11)

x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x[5:]


array([ 5,  6,  7,  8,  9, 10])

In [ ]:
x[10::]

array([10])

In [ ]:
x 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x[1:6]

array([1, 2, 3, 4, 5])

In [ ]:
x[1::5]

array([1, 6])

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

mult_arr = np.array_split(arr, 3, axis=1)

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[:, np.newaxis]



array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [ ]:
arr[0:3:1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]] )

arr_toplam = np.concatenate([arr, arr2])

In [ ]:
arr_toplam


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

Skildim saldim 


                                                        --  The Slowness of Loops --


In [ ]:
a2 = np.arange(9)

In [ ]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(a2/1)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


Reshaping of arrays 

In [31]:
import numpy as np

grid = np.arange(1, 10)

deneme = np.arange(10, 19)
 
 
combine = np.concatenate([grid, deneme])

print(combine)




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


-- Reshape --

In [37]:
rehaped_horizontal= combine.reshape((1, 18))

print(rehaped_horizontal)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]]


In [42]:
rehaped_vertical = combine.reshape((18, 1))

print(rehaped_vertical)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]]


In [44]:
rehaped_vertical = combine.reshape((9, 2))

print(rehaped_vertical)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]


In [45]:
rehaped_vertical = combine.reshape((2, 9))

print(rehaped_vertical)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


-- Spliting of arrays --

In [52]:
x = [1,2,3,99,99,3,2,1]

x1, x2 = np.split(x,[4])

print(x1, x2)

[ 1  2  3 99] [99  3  2  1]


In [60]:
x = [1,1,1,1,1,2,2,2,3,3,4,4,4]

x1, x2, x3, x4= np.split(x,[5,8,10])

print(x1,x2,x3, x4)

[1 1 1 1 1] [2 2 2] [3 3] [4 4 4]


Summig the values in an array 

In [61]:
import numpy as pd 


In [63]:
L = np.random.random(100)
print(L)

[0.48630567 0.20762186 0.10551024 0.20126691 0.64820646 0.40049474
 0.98313569 0.13709521 0.68661019 0.83999515 0.22891901 0.90626421
 0.11723407 0.2190193  0.73239259 0.56592596 0.32291755 0.07346654
 0.28358476 0.43190306 0.88894744 0.97409072 0.50061406 0.49377656
 0.96166193 0.88676275 0.63755922 0.83713434 0.75339292 0.738112
 0.51285912 0.02126044 0.65903372 0.24492603 0.94984561 0.54724228
 0.03986161 0.8453897  0.21242798 0.34963598 0.49892784 0.74429571
 0.61934046 0.70148312 0.23654625 0.99413222 0.57987426 0.71419091
 0.56641952 0.94474057 0.30059761 0.4013958  0.2103497  0.09151132
 0.97533855 0.27749181 0.32599976 0.3717961  0.36813618 0.36046463
 0.67360094 0.16627284 0.39072646 0.48462289 0.40695372 0.92261482
 0.65530614 0.52660064 0.66947742 0.14837205 0.89921779 0.30305414
 0.17598875 0.59586591 0.81275614 0.10835054 0.61152088 0.28522305
 0.00827222 0.06054352 0.78113582 0.03998357 0.77696246 0.70751586
 0.44555162 0.38383892 0.15292074 0.52585381 0.86178453 0.656033

In [64]:
sum(L)

50.077374141546336

In [65]:
big_array = np.random.random(100000)
%timeit sum (big_array)
%timeit np.sum(big_array)


3.61 ms ± 31.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
22.4 µs ± 94.4 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [68]:
min(big_array), max(big_array)

(5.699654063939796e-06, 0.9999965823286819)

multi dimensional aggregates 

In [74]:
Random = np.random.random((5,5))
Random

array([[0.90496681, 0.54045118, 0.78217073, 0.77156539, 0.61628749],
       [0.66922578, 0.45189769, 0.34138095, 0.05597649, 0.66975665],
       [0.95331842, 0.7551607 , 0.07288416, 0.69338786, 0.66019867],
       [0.36950192, 0.86309885, 0.5009385 , 0.03734745, 0.70354955],
       [0.98880686, 0.03370073, 0.28259246, 0.84504191, 0.85673417]])

In [75]:
Random.sum()

14.419941369551935