Evet, Pandas Ögreniyoruz bu gün. Gooo brrr

In [14]:
#Niyet ettim allah rizasi icin Pandas import etmeye 

import pandas as pd
import numpy as np


In [15]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [16]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [17]:
#Bunu anlamadim
data.index

RangeIndex(start=0, stop=4, step=1)

In [18]:
data[1:4]

1    0.50
2    0.75
3    1.00
dtype: float64

In [27]:
data_abc = pd.Series([1.1,2.2,3.3,4.4], 
                     index=['a', 'b', 'c','d'])

data_abc

a    1.1
b    2.2
c    3.3
d    4.4
dtype: float64

In [30]:
data_abc['b']

2.2

In [35]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [38]:
tpop = population["Texas"]

Cpop = population["California"]

In [47]:
po =pd.Series(["tpop" ,"Cpop"])
po

0    tpop
1    Cpop
dtype: object

In [48]:
128/50

2.56

In [52]:
data_Frame = pd.DataFrame({"population of Cities": population})

data_Frame

population of Cities
California              38332521
Texas                   26448193
New York                19651127
Florida                 19552860
Illinois                12882135

In [55]:
cities_oberf = pd.Series({"California": 12480, "Texas": 12412, "New York": 15234, "Illinois": 28839, "Florida": 9173})

cities_oberf

California    12480
Texas         12412
New York      15234
Illinois      28839
Florida        9173
dtype: int64

In [57]:
data_Frame = pd.DataFrame({"population of Cities": population, 
                           "Size": cities_oberf})

data_Frame

population of Cities   Size
California              38332521  12480
Florida                 19552860   9173
Illinois                12882135  28839
New York                19651127  15234
Texas                   26448193  12412

In [74]:
cities_oberf


California    12480
Texas         12412
New York      15234
Illinois      28839
Florida        9173
dtype: int64

In [75]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [80]:
yogunluk = cities_oberf["cities_oberf"] / population["population"]

KeyError: 'cities_oberf'

Tr sehirlerinin yüz ölcumu, Popülasyonu ve yeüz ölcüme dusen popülasyon Yogunlugunu yapicam simdi, IIIIzzzleeee

In [1]:
import pandas as pd 



In [12]:
tr_pop = pd.Series({"Beylikdüzü": 250_000, 'Sariyer': 100_000, 'Fatih': 300_000, 'MALtepe': 300_000, 'Cekmece': 350_000, 'Besiktas': 500_000})

tr_area = pd.Series({"Beylikdüzü": 1300, 'Sariyer': 32400, 'Fatih': 81241, 'MALtepe': 812940, 'Cekmece': 3512, 'Besiktas': 7123})

tr_density =  tr_pop / tr_area
data = pd.DataFrame({'Populasyon': tr_pop, 'Yüz olcumu': tr_area, 'metre kara basina kelle': tr_density})



data.T

Beylikdüzü       Sariyer          Fatih  \
Populasyon               250000.000000  100000.00000  300000.000000   
Yüz olcumu                 1300.000000   32400.00000   81241.000000   
metre kara basina kelle     192.307692       3.08642       3.692717   

                               MALtepe        Cekmece       Besiktas  
Populasyon               300000.000000  350000.000000  500000.000000  
Yüz olcumu               812940.000000    3512.000000    7123.000000  
metre kara basina kelle       0.369031      99.658314      70.195142

In [13]:
data

Populasyon  Yüz olcumu  metre kara basina kelle
Beylikdüzü      250000        1300               192.307692
Sariyer         100000       32400                 3.086420
Fatih           300000       81241                 3.692717
MALtepe         300000      812940                 0.369031
Cekmece         350000        3512                99.658314
Besiktas        500000        7123                70.195142

In [14]:
data.values

array([[2.50000000e+05, 1.30000000e+03, 1.92307692e+02],
       [1.00000000e+05, 3.24000000e+04, 3.08641975e+00],
       [3.00000000e+05, 8.12410000e+04, 3.69271673e+00],
       [3.00000000e+05, 8.12940000e+05, 3.69030925e-01],
       [3.50000000e+05, 3.51200000e+03, 9.96583144e+01],
       [5.00000000e+05, 7.12300000e+03, 7.01951425e+01]])

In [15]:
data.values[0
            ]

array([2.50000000e+05, 1.30000000e+03, 1.92307692e+02])

In [16]:
data.iloc[:3 ,:2]

Populasyon  Yüz olcumu
Beylikdüzü      250000        1300
Sariyer         100000       32400
Fatih           300000       81241

In [17]:
data.iloc[:2, :3]

Populasyon  Yüz olcumu  metre kara basina kelle
Beylikdüzü      250000        1300               192.307692
Sariyer         100000       32400                 3.086420

AttributeError: 'DataFrame' object has no attribute 'ix'

In [22]:
#ix falan filan cok anlamadim ama dewam 

Operating on Data in Pandas
